### ISSUE TITLE
4th relay control

### ISSUE THREAD

**Issue by mandonych** [tanilolli/LZ1AQ-Loop-Controller#3]
Thanks for making this project.
I find it very useful and easy to make. I made one for myself and had the idea to turn off the amplifier when the antenna is not in use. I control an antenna that is located in another building over a local network.
Is it possible to make independent control of the fourth relay, because it is not used? Add another button or switch (On/Off) to control it. It could be used to cut off power from the amplifier's power supply when the antenna is not in use. Of course, your code is not so complicated, with detailed comments, but unfortunately my knowledge is not enough for this. I can only edit the code to build it in Visual Studio Code.

**Comment by anthonydiiorio** [comment]
Hi Alex, thanks for the suggestion. I've implemented an option to control the 4th relay. 

Relay 4 connects to pin D1 (GPIO 5)
You can enable the 4th relay by setting `bool auxEnable = true;`
You can set the button label by changing `const char *auxLabel = "Relay 4";`

**Comment by mandonych** [comment]
Awesome, thanks for the quick response. This is exactly what I needed. I hope this will also be useful to someone.

**Comment by anthonydiiorio** [comment]
Thanks, yup I just wired my unit to control the power supply as well. I added an option to set the button colors for normally closed as well. 

You can invert the button color for normally closed by setting `bool auxNC = true;`

![aux-relay](https://user-images.githubusercontent.com/1933848/184038821-3cb957f7-238c-43fc-8ac0-ee4f3eedc273.png)

![image](https://user-images.githubusercontent.com/1933848/184038876-1c03e5f1-9b2b-4ed6-8da7-e96f28c40b87.png)
